### ISSUE TITLE
Issues with kts scripts

### ISSUE THREAD

**Issue by FlorentinV-Decathlon** [structurizr/lite#67] opened 2023-06-21 09:22 UTC
### Description

Hello, I am facing the following error while browsing the site : `java.lang.RuntimeException: Could not load a scripting engine for extension "kts"`.

Maybe you have an idea?

The issue seems to be similar to this one : [https://github.com/structurizr/lite/issues/33](https://github.com/structurizr/lite/issues/33)

### Steps to reproduce

I haven't found a way to systematically reproduce the bug, but these steps produced an error for me :

1. Navigate to documentation
2. Navigate to Diagrams
3. Repeat the operations several times

### Screenshot

![image](https://github.com/structurizr/lite/assets/123394734/2e7807e7-dce1-46c5-a1b8-b012c5f91036)

### Code sample

```text
workspace {

    model {
        user = person "User"
        softwareSystem = softwareSystem "Software System" {
            test_container = container "Test Container" {
                description "test_container"
                tags "test"
                technology "TEST TECHNOLOGY"
            }
        }

        user -> softwareSystem "Uses"
    }

    # https://github.com/structurizr/dsl/blob/master/docs/language-reference.md#scripts
    !script scripts/copy_containers_tech_as_tags.kts



    views {
        systemContext softwareSystem "Diagram1" {
            include *
            autoLayout
        }
        container softwareSystem "Diagram2" {
            include *
            autoLayout
        }
    }

}
```

### Structurizr versions
- build: 3078 (2023-06-19T15:14:49Z
- structurizr-java: v1.24.1
- structurizr-dsl: v1.30.1
- structurizr-import: v1.4.1

### Device 
- **macOS** :13.4 (22F66)
- **chip** : Apple M1 Pro

### Severity

Minor

### Priority

Low

### Resolution

I have no budget, please fix this for free

### More information

Content of `scripts/copy_containers_tech_as_tags.kts` :

``` 
import com.structurizr.model.*

// For each container, append defined Technology as new Tag
// in order to help styling (styles are based on tags)
workspace.model.softwareSystems.forEach { ss: SoftwareSystem ->
    ss.containers.forEach { co: Container ->
        val tech: String? = co.technology?.trim()
        if (!tech.isNullOrEmpty()) {
            co.addTags(tech)
        }
    }
}
```

**Comment by simonbrowndotje** [comment] 2023-06-21 09:31
It works for me. Are you using the pre-built Docker image, building your own, or using the `.war` file?

<img width="1728" alt="Screenshot 2023-06-21 at 10 30 05" src="https://github.com/structurizr/lite/assets/1009874/0fa7889d-ebbe-484a-a56d-87d5a2b7ba9c">

**Comment by FlorentinV-Decathlon** [comment] 2023-06-23 09:46
I use the image published on Dockerhub `structurizr/lite:last`

Here is the signature I got with the command `docker inspect structurizr/lite:latest --format ‘{{.Id}}’` : `‘sha256:2ba22e2783450899c936cf28abc21ba1485210a04c0d0f4a96426dd82450b400’`

**Comment by simonbrowndotje** [comment] 2023-09-21 11:41
Closing this issue ... feel free to reopen if you find a way to reproduce it.

**Closed by simonbrowndotje** 2023-09-21 11:41 UTC
Labels: bug
