### ISSUE TITLE
Please. Provide documentation for ADR link feature and how to see it in Decision Explorer

### ISSUE THREAD

**Issue by comdiv** [structurizr/lite#93] opened 2023-09-27 04:26 UTC
### Description

1. Where to place links? (i've tried Status segment, Context segment)
2. What is a format exactly:
    - trys `(Some Text)[./0002-some-adr.md]` - not working at all (cannot navigate with MD, not seen in Explorer)
    - trys `(Some Text)[0002-some-adr.md]` - same
    - trys `(Some Text)[#2]` - starts work in MD itself (can navigate from one ADR to another), but Explorer still not sees links

### Priority

Medium

### Resolution

I have no budget and there's no rush, please add this feature for free

**Comment by simonbrowndotje** [comment] 2023-09-28 11:22
Closing - duplicate of #92.

**Closed by simonbrowndotje** 2023-09-28 11:22 UTC
Labels: enhancement
