### ISSUE TITLE
No output in browser on Windows 11 running the Jar file

### ISSUE THREAD

**Issue by BruceEckel** [structurizr/lite#72] opened 2023-07-05 17:52 UTC
### Description

Following these instructions:
https://structurizr.com/share/76352/documentation#open-your-web-browser
I go to http://localhost:8080/
I get a blank browser page along with the "loading" spinner in the browser tab.

If I CTRL-C out of the app running on the console, then I immediately see this:
![image](https://github.com/structurizr/lite/assets/1001900/2fa231ab-8cc2-4cc3-8422-35f3947c50b5)

But that only happens sometimes.

There was one attempt where I seemed to be able to get it working, even editing the `workspace.dsl`, getting an (appropriate) error message and fixing it and reloading the page to regenerate the diagram. But it's unclear to me how I accomplished this; so far it appears random whether a particular command-line invocation is going to successfully produce a browser page.

### Steps to reproduce

1. Start program in the Powershell Console:
```
java "-Djdk.util.jar.enableMultiRelease=false" -jar structurizr-lite-3087.war C:\git\python-experiments\C4-DSL
```
2. Open http://localhost:8080/
3. The generated workspace.dsl (slightly modified):
```
workspace {

    model {
        user = person "Bob"
        softwareSystem = softwareSystem "Robotic Storage System"

        user -> softwareSystem "Uses"
    }

    views {
        systemContext softwareSystem "Foo_Bar" {
            include *
            autoLayout
        }
    }

}
```
4. The generated workspace.json (unmodified):
```
{
  "id" : 1,
  "name" : "Name",
  "description" : "Description",
  "lastModifiedDate" : "2023-07-05T17:30:01Z",
  "properties" : {
    "structurizr.dsl" : "d29ya3NwYWNlIHsNCg0KICAgIG1vZGVsIHsNCiAgICAgICAgdXNlciA9IHBlcnNvbiAiQm9iIg0KICAgICAgICBzb2Z0d2FyZVN5c3RlbSA9IHNvZnR3YXJlU3lzdGVtICJSb2JvdGljIFN0b3JhZ2UgU3lzdGVtIg0KDQogICAgICAgIHVzZXIgLT4gc29mdHdhcmVTeXN0ZW0gIlVzZXMiDQogICAgfQ0KDQogICAgdmlld3Mgew0KICAgICAgICBzeXN0ZW1Db250ZXh0IHNvZnR3YXJlU3lzdGVtICJGb29fQmFyIiB7DQogICAgICAgICAgICBpbmNsdWRlICoNCiAgICAgICAgICAgIGF1dG9MYXlvdXQNCiAgICAgICAgfQ0KICAgIH0NCg0KfQ0K"
  },
  "configuration" : { },
  "model" : {
    "people" : [ {
      "id" : "1",
      "tags" : "Element,Person",
      "properties" : {
        "structurizr.dsl.identifier" : "user"
      },
      "name" : "Bob",
      "relationships" : [ {
        "id" : "3",
        "tags" : "Relationship",
        "properties" : {
          "structurizr.dsl.identifier" : "40283aa9-5fc2-43c6-98d2-f585918a5020"
        },
        "sourceId" : "1",
        "destinationId" : "2",
        "description" : "Uses"
      } ],
      "location" : "Unspecified"
    } ],
    "softwareSystems" : [ {
      "id" : "2",
      "tags" : "Element,Software System",
      "properties" : {
        "structurizr.dsl.identifier" : "softwaresystem"
      },
      "name" : "Robotic Storage System",
      "location" : "Unspecified",
      "documentation" : { }
    } ]
  },
  "documentation" : { },
  "views" : {
    "systemContextViews" : [ {
      "key" : "Foo_Bar",
      "order" : 1,
      "softwareSystemId" : "2",
      "automaticLayout" : {
        "implementation" : "Graphviz",
        "rankDirection" : "TopBottom",
        "rankSeparation" : 300,
        "nodeSeparation" : 300,
        "edgeSeparation" : 0,
        "vertices" : false
      },
      "enterpriseBoundaryVisible" : true,
      "relationships" : [ {
        "id" : "3"
      } ],
      "elements" : [ {
        "id" : "1",
        "x" : 0,
        "y" : 0
      }, {
        "id" : "2",
        "x" : 0,
        "y" : 0
      } ]
    } ],
    "configuration" : {
      "branding" : { },
      "styles" : { },
      "terminology" : { },
      "lastSavedView" : "Foo_Bar"
    }
  }
}
```

### Code sample

```text
Powershell console output:

2023-07-05T11:44:43.383-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : Starting StructurizrLite using Java 20.0.1 with PID 9584 (C:\tools\structurizr-lite-3087.war started by bruce in C:\tools)
2023-07-05T11:44:43.395-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : No active profile set, falling back to 1 default profile: "default"
2023-07-05T11:45:00.661-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : Started StructurizrLite in 18.372 seconds (process running for 21.318)
2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : ***********************************************************************************
2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :   _____ _                   _              _
2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :  / ____| |                 | |            (_)
2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : | (___ | |_ _ __ _   _  ___| |_ _   _ _ __ _ _____ __
2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :  \___ \| __| '__| | | |/ __| __| | | | '__| |_  / '__|
2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :  ____) | |_| |  | |_| | (__| |_| |_| | |  | |/ /| |
2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : |_____/ \__|_|   \__,_|\___|\__|\__,_|_|  |_/___|_|
2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :

2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : Structurizr Lite
2023-07-05T11:45:00.674-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :  - build: 3087 (2023-07-03T16:28:01Z
2023-07-05T11:45:00.685-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :  - structurizr-java: v1.24.1
2023-07-05T11:45:00.738-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :  - structurizr-dsl: v1.30.2
2023-07-05T11:45:00.745-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :  - structurizr-import: v1.4.1
2023-07-05T11:45:00.745-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :
2023-07-05T11:45:00.745-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : Workspace path: C:\git\python-experiments\C4-DSL
2023-07-05T11:45:00.745-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : Workspace filename: workspace[.dsl|.json]
2023-07-05T11:45:00.745-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : URL:
2023-07-05T11:45:00.745-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : Auto-save interval: 5000ms
2023-07-05T11:45:00.745-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : Auto-refresh interval: 0ms
2023-07-05T11:45:00.817-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : dot: available
2023-07-05T11:45:00.817-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : ***********************************************************************************
2023-07-05T11:45:00.817-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : MIT License
2023-07-05T11:45:00.817-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :
2023-07-05T11:45:00.817-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : Copyright (c) 2023 Structurizr Limited
2023-07-05T11:45:00.817-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :
2023-07-05T11:45:00.817-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : Permission is hereby granted, free of charge, to any person obtaining a copy
2023-07-05T11:45:00.817-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : of this software and associated documentation files (the "Software"), to deal
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : in the Software without restriction, including without limitation the rights
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : copies of the Software, and to permit persons to whom the Software is
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : furnished to do so, subject to the following conditions:
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : The above copyright notice and this permission notice shall be included in all
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : copies or substantial portions of the Software.
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     :
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
2023-07-05T11:45:00.826-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
2023-07-05T11:45:00.833-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
2023-07-05T11:45:00.834-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
2023-07-05T11:45:00.834-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
2023-07-05T11:45:00.834-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : SOFTWARE.
2023-07-05T11:45:00.834-06:00  INFO 9584 --- [           main] com.structurizr.lite.StructurizrLite     : ***********************************************************************************
```

### Configuration

```
 7/3/2023 11:39 AM      125042412 structurizr-lite-3087.war

PS C:\tools> java --version
openjdk 20.0.1 2023-04-18
OpenJDK Runtime Environment (build 20.0.1+9-29)
OpenJDK 64-Bit Server VM (build 20.0.1+9-29, mixed mode, sharing)


Host Name:                 DESKTOP-25UJOVE
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Organization:   N/A
Original Install Date:     12/10/2022, 7:24:40 PM
System Boot Time:          6/29/2023, 11:57:39 AM
System Manufacturer:       Microsoft Corporation
System Model:              Surface Pro 7
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 126 Stepping 5 GenuineIntel ~1298 Mhz
BIOS Version:              Microsoft Corporation 15.11.140, 7/8/2022
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-07:00) Mountain Time (US & Canada)
Total Physical Memory:     15,970 MB
Available Physical Memory: 6,037 MB
Virtual Memory: Max Size:  16,994 MB
Virtual Memory: Available: 4,185 MB
Virtual Memory: In Use:    12,809 MB

### Severity

Critical

### Priority

High

### Resolution

I have no budget, please fix this for free

### More information

I'm going to try the Docker version to see if that works any better.

**Comment by BruceEckel** [comment] 2023-07-05 18:11
Not sure if this helps: when I start with an empty Structurizr data directory, starting the app will produce a `workspace.dsl` file, and then when I try to open the browser the `workspace.json` file appears.

**Comment by BruceEckel** [comment] 2023-07-05 18:29
The Docker version seems to work consistently.

**Comment by BruceEckel** [comment] 2023-07-05 19:33
Just installed the Docker version on my desktop (the other was on my laptop) and it started seamlessly. (also a Windows 11 machine).

**Comment by simonbrowndotje** [comment] 2023-07-06 06:33
Thanks for the information. Do you see any errors in your web browser's developer/JavaScript console? I'm wondering whether this is a problem with running Graphviz ... does commenting out `autoLayout` in your `workspace.dsl` file resolve the issue?

**Comment by BruceEckel** [comment] 2023-07-10 16:56
I removed all autoLayouts. Here's the browser javascript console:

```
LegacyDataMixin will be applied to all legacy elements.
Set `_legacyUndefinedCheck: true` on element class to enable.
DevTools failed to load source map: Could not load content for chrome-extension://akimgimeeoiognljlfchpbkpfbmeapkh/polyfills/web-animations-next-lite.min.js.map: System error: net::ERR_FILE_NOT_FOUND
```

After removing the autoLayouts, I got the following on the windows terminal used for invoking the command (after the usual copyright stuff):

```
2023-07-10T10:44:30.396-06:00  WARN 20844 --- [nio-8080-exec-1] com.structurizr.dsl.AbstractViewParser   : Container-001 is an automatically generated view key - you will likely lose manual layout information when using automatically generated view keys.
2023-07-10T10:44:30.422-06:00  WARN 20844 --- [nio-8080-exec-1] com.structurizr.dsl.AbstractViewParser   : Component-001 is an automatically generated view key - you will likely lose manual layout information when using automatically generated view keys.
2023-07-10T10:44:30.429-06:00  WARN 20844 --- [nio-8080-exec-1] com.structurizr.dsl.AbstractViewParser   : Component-002 is an automatically generated view key - you will likely lose manual layout information when using automatically generated view keys.
2023-07-10T10:44:31.073-06:00  WARN 20844 --- [nio-8080-exec-1] com.structurizr.view.ViewSet             : Could not find a matching view for "System Landscape" ... diagram layout information may be lost.
2023-07-10T10:44:31.073-06:00  WARN 20844 --- [nio-8080-exec-1] com.structurizr.view.ViewSet             : Could not find a matching view for "C4 Dsl Extension - Containers" ... diagram layout information may be lost.
2023-07-10T10:44:31.078-06:00  WARN 20844 --- [nio-8080-exec-1] com.structurizr.view.ViewSet             : Could not find a matching view for "C4 Dsl Extension - C4 DSL Client - Components" ... diagram layout information may be lost.
```

At this point I've stopped attempting to get the war file to work, since the docker version not only works but starts up faster. My guess is that it wouldn't be an impediment to narrow the instructions to just using the docker version, at least for windows. Especially since that seems to have a reliable testing process. (Insert requisite joke about "Java, write once run everywhere").

**Comment by WolfgangNiebuhr** [comment] 2023-11-03 13:30
I have a similar problem with the current structurizr-lite.war version. When I run that on a (virtual) machine with no internet access at all. The same dsl and war runs fine on another machine with http(s) internet access.

More info: the browser shows a lot of Server errros (500) 

GET https://fonts.googleapis.com/css?family=Open+Sans:400,700 net::ERR_NAME_NOT_RESOLVED
structurizr-ui.js:1 Uncaught TypeError: Cannot set properties of undefined (setting 'DEFAULT_FONT_NAME')
    at structurizr-ui.js:1:34
(anonymous) @ structurizr-ui.js:1
diagrams:368 Uncaught TypeError: Cannot set properties of undefined (setting 'ProgressMessage')
    at diagrams:368:36
(anonymous) @ diagrams:368
diagrams:415 Uncaught TypeError: Cannot set properties of undefined (setting 'QuickNavigation')
    at diagrams:415:36
(anonymous) @ diagrams:415
diagrams:681 Uncaught TypeError: Cannot set properties of undefined (setting 'Tooltip')
    at diagrams:681:28
(anonymous) @ diagrams:681
jquery-3.6.3.min.js:2 
        
        
       POST http://localhost:8080/error 500 (Internal Server Error)
send @ jquery-3.6.3.min.js:2
ajax @ jquery-3.6.3.min.js:2
logError @ structurizr.js:54
window.onerror @ structurizr.js:49
error (async)
(anonymous) @ structurizr.js:48
structurizr.js:71 There was an error logging the error : error (HTTP status code=500)
diagrams:2137 Uncaught ReferenceError: progressMessage is not defined
    at diagrams:2137:5
(anonymous) @ diagrams:2137
diagrams:3406 Uncaught TypeError: Cannot read properties of undefined (reading 'StructurizrApiClient')
    at diagrams:3406:53
(anonymous) @ diagrams:3406
jquery-3.6.3.min.js:2 
        
        
       POST http://localhost:8080/error 500 (Internal Server Error)
send @ jquery-3.6.3.min.js:2
ajax @ jquery-3.6.3.min.js:2
logError @ structurizr.js:54
window.onerror @ structurizr.js:49
error (async)
(anonymous) @ structurizr.js:48
structurizr.js:71 There was an error logging the error : error (HTTP status code=500)
jquery-3.6.3.min.js:2 
        
        
       POST http://localhost:8080/error 500 (Internal Server Error)
send @ jquery-3.6.3.min.js:2
ajax @ jquery-3.6.3.min.js:2
logError @ structurizr.js:54
window.onerror @ structurizr.js:49
error (async)
(anonymous) @ structurizr.js:48
structurizr.js:71 There was an error logging the error : error (HTTP status code=500)
jquery-3.6.3.min.js:2 
        
        
       POST http://localhost:8080/error 500 (Internal Server Error)
send @ jquery-3.6.3.min.js:2
ajax @ jquery-3.6.3.min.js:2
logError @ structurizr.js:54
window.onerror @ structurizr.js:49
error (async)
(anonymous) @ structurizr.js:48
structurizr.js:71 There was an error logging the error : error (HTTP status code=500)
jquery-3.6.3.min.js:2 
        
        
       POST http://localhost:8080/error 500 (Internal Server Error)
send @ jquery-3.6.3.min.js:2
ajax @ jquery-3.6.3.min.js:2
logError @ structurizr.js:54
window.onerror @ structurizr.js:49
error (async)
(anonymous) @ structurizr.js:48
structurizr.js:71 There was an error logging the error : error (HTTP status code=500)
jquery-3.6.3.min.js:2 
        
        
       POST http://localhost:8080/error 500 (Internal Server Error)
send @ jquery-3.6.3.min.js:2
ajax @ jquery-3.6.3.min.js:2
logError @ structurizr.js:54
window.onerror @ structurizr.js:49
error (async)
(anonymous) @ structurizr.js:48
structurizr.js:71 There was an error logging the error : error (HTTP status code=500)

**Comment by BruceEckel** [comment] 2023-11-03 14:08
I found that running it in Docker worked fine.

*Bruce Eckel*
HappyPathProgramming.com
SummerTechForum.com
MindViewLLC.com
Blog: BruceEckel.com
EvolveWork.co
WinterTechForum.com <http://www.WinterTechForum.com>
OnJava8.com <http://www.OnJava8.com>
www.AtomicKotlin.com
Reinventing-Business.com <http://www.Reinventing-Business.com>

**Comment by simonbrowndotje** [comment] 2023-12-28 10:57
Closing as can't reproduce.

**Closed by simonbrowndotje** 2023-12-28 10:57 UTC
Labels: can't reproduce
