### ISSUE TITLE
"MD5 hash doesn't match content" modal window

### ISSUE THREAD

**Issue by FightingFox** [structurizr/lite#91] opened 2023-09-13 06:50 UTC
### Question

Good day!
I use Structurizr in docker container, and I see "MD5 hash doesn't match content" always. What can I fix it?
Thanks.

![Снимок экрана 2023-09-13 в 09 49 48](https://github.com/structurizr/dsl/assets/77280748/c66f0dc7-528e-4c25-b0cf-c938cef6d3f7)

**Comment by simonbrowndotje** [comment] 2023-09-22 08:13
Is it locally installed and accessed via a `http://localhost:8080` address? And what's your workflow? Does the basic [quickstart](https://docs.structurizr.com/lite/quickstart) work for you? Have you tried another web browser, possibly in private mode to clear all session information?

**Comment by FightingFox** [comment] 2023-09-22 08:55
UPD:
In private mode i have problem too.

**Comment by simonbrowndotje** [comment] 2023-09-22 09:07
I've booted up Lite on 8080 and 8081 and both work fine for me, so I can't reproduce it I'm afraid. Other than (1) ensuring you have no rogue web browser windows/tabs open that may be interfering and (2) moving Docker from 8080 to another port, I don't have any other suggestions.

**Comment by simonbrowndotje** [comment] 2023-12-28 10:56
Closing as can't reproduce - feel free to reopen with some additional information.

**Closed by simonbrowndotje** 2023-12-28 10:56 UTC
Labels: can't reproduce
